spring:
  application:
    name: microservice-template

  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 3000
        max-interval: 5000
        multiplier: 1.2

  config:
    import: configserver:${CONFIG_SERVER_URI:http://localhost:8888}

  profiles:
    default: dev